# -*- coding: utf-8 -*-
{
    "name": "Kojto Finance",
    "version": "18.04.07",
    "category": "KOJTO",
    "description": "Finance management module with invoices, cashflow, accounting, and AI-powered auto-accounting features",
    "author": "KOJTO",
    "website": "https://www.kojto.com",
    "post_init_hook": "post_init_hook",
    "depends": ["kojto_hr", "kojto_assets"],
    "data": [
        "security/ir.model.access.csv",
        "views/kojto_finance_invoices_views.xml",
        "views/kojto_finance_invoices_accounting_views.xml",
        "views/kojto_finance_cashflow_views.xml",
        "views/kojto_finance_cashflow_allocation_views.xml",
        "views/kojto_finance_invoice_contents_views.xml",
        "views/kojto_finance_bank_statements_views.xml",
        "views/kojto_finance_bank_statements_import_view.xml",
        "views/kojto_finance_accounting_templates_views.xml",
        "views/kojto_finance_accounting_identifiers_views.xml",
        "views/kojto_finance_accounting_types_views.xml",
        "views/kojto_finance_accounting_subtypes_views.xml",
        "views/kojto_finance_accounting_accounts_views.xml",
        "views/kojto_finance_accounting_ops_views.xml",
        "views/kojto_finance_accounts_balance_report_views.xml",
        "views/kojto_finance_invoice_content_import_wizard_views.xml",
        "views/kojto_finance_vat_treatment_views.xml",
        "views/dashboards/kojto_finance_revenue_expense_dashboard_list_views.xml",
        "views/dashboards/kojto_finance_cashflow_dashboard_list_views.xml",
        'views/dashboards/kojto_finance_time_tracking_dashboard_list_views.xml',
        'views/dashboards/kojto_finance_asset_works_dashboard_list_views.xml',
        "views/dashboards/kojto_finance_vat_balance_dashboard_list_views.xml",
        "wizards/views/kojto_finance_balance_wizard_views.xml",
        "wizards/views/kojto_finance_balance_company_line_breakdown_views.xml",
        "wizards/views/kojto_finance_balance_maincode_line_breakdown_views.xml",
        "wizards/views/kojto_finance_balance_code_line_breakdown_views.xml",
        "wizards/views/kojto_finance_balance_subcode_line_breakdown_views.xml",
        "views/dashboards/kojto_finance_open_amount_dashboard_views.xml",
        "views/dashboards/kojto_finance_counterparty_balance_dashboard_views.xml",
        "views/kojto_finance_menu_views.xml",
        "views/kojto_finance_buttons.xml",
        "reports/kojto_finance_invoice_reports.xml",
        "reports/kojto_finance_invoice_templates.xml",
        "reports/kojto_finance_invoice_company_lang_templates.xml",
    ],
    "installable": True,
    "application": True,
    "auto_install": False,
}
