# -*- coding: utf-8 -*-
{
    "name": "Kojto Base",
    "summary": "Base module with common data models and utilities",
    "description": "Core module providing base data models for banks, addresses, tax numbers, units, certificates, and other common entities used across KOJTO modules",
    "author": "KOJTO",
    "website": "https://www.kojto.com",
    "category": "KOJTO",
    "version": "18.04.07",
    "depends": ["kojto_landingpage", "kojto_library"],
    "data": [
        "data/res.groups.csv",
        "data/kojto.base.banks.csv",
        "data/cron_job.xml",
        "security/ir.model.access.csv",
        "views/kojto_base_banks_views.xml",
        "views/kojto_base_bank_accounts_views.xml",
        "views/kojto_base_certificates_views.xml",
        "views/kojto_base_currency_exchange_views.xml",
        "views/kojto_base_incoterms_views.xml",
        "views/kojto_base_material_grades_views.xml",
        "views/kojto_base_payment_terms_views.xml",
        "views/kojto_base_tax_numbers_views.xml",
        "views/kojto_base_units_views.xml",
        "views/kojto_base_stores_views.xml",
        "views/kojto_base_images_views.xml",
        "views/kojto_base_predefined_texts_views.xml",
        "views/kojto_base_buttons.xml",
        "views/kojto_base_menu_views.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "/kojto_base/static/src/css/*.*",
            "/kojto_base/static/src/js/*.*",
        ],
    },
    "installable": True,
    "application": True,
    "auto_install": False,
}
