{
    "name": "Kojto Deliveries",
    "version": "18.04.07",
    "category": "KOJTO",
    "description": "Delivery management module for managing deliveries, packages, CMR documents, packaging materials, inspection certificates, and delivery reports",
    "author": "KOJTO",
    "website": "https://www.kojto.com",
    "depends": ["kojto_warehouses"],
    "data": [
        "security/ir.model.access.csv",
        "views/kojto_deliveries_views.xml",
        "views/kojto_delivery_contents_views.xml",
        "views/kojto_delivery_cmr_views.xml",
        "views/kojto_delivery_packaging_materials_views.xml",
        "views/kojto_delivery_package_contents_views.xml",
        "views/kojto_delivery_packaging_material_items_views.xml",
        "views/kojto_delivery_packages_views.xml",
        "views/kojto_delivery_consumed_materials_views.xml",
        "views/kojto_delivery_inspection_certificates_views.xml",
        "views/kojto_delivery_menu_views.xml",
        "views/kojto_deliveries_buttons.xml",
        "views/kojto_delivery_content_import_wizard_views.xml",
        "reports/kojto_delivery_reports.xml",
        "reports/kojto_delivery_templates.xml",
        'reports/kojto_delivery_packages_templates.xml',
        'reports/kojto_delivery_origin_declaration_templates.xml',
        'reports/kojto_delivery_export_declaration_templates.xml',
        'reports/kojto_delivery_dual_use_declaration_templates.xml',
        'reports/kojto_delivery_package_label_templates.xml',
        'reports/kojto_delivery_cmr_templates.xml',
        'reports/kojto_delivery_inspection_certificate_templates.xml',
        'reports/kojto_delivery_consumed_materials_templates.xml',
    ],
    "assets": {
        "web.assets_backend": [
            "/kojto_deliveries/static/css/kojto_delivery.css",
        ],
    },
    "installable": True,
    "application": True,
    "auto_install": False,
}
