{
    "name": "Kojto Assets",
    "version": "18.04.07",
    "category": "KOJTO",
    "description": "Asset management module for tracking assets, asset works, bookings, maintenance, values, and subcode rates",
    "author": "KOJTO",
    "website": "https://www.kojto.com",
    "depends": ["kojto_library", "kojto_base", "kojto_commission_codes"],
    "data": [
        "security/ir.model.access.csv",
        "views/kojto_assets_views.xml",
        "views/kojto_asset_works_views.xml",
        "views/kojto_asset_booking_views.xml",
        "views/kojto_asset_maintenance_views.xml",
        "views/kojto_asset_value_views.xml",
        "views/kojto_asset_subcode_rates_views.xml",
        "views/kojto_asset_subcode_rates_dashboard_views.xml",
        "views/kojto_assets_buttons.xml",
        "views/kojto_assets_menu_views.xml",
        "reports/kojto_assets_report_actions.xml",
        "reports/kojto_assets_report_templates.xml",
    ],
    "installable": True,
    "application": True,
    "auto_install": False,
}
