{
    "name": "Kojto EN1090",
    "version": "18.04.08",
    "category": "KOJTO",
    "summary": "EN1090 Documentation Management",
    "description": "This module manages EN1090 documentation",
    "author": "KOJTO",
    "website": "https://www.kojto.com",
    "depends": [
        "base",
        "web",
        "kojto_technical_docs",
        "kojto_contracts",
        "kojto_factory",
    ],
    "data": [
        "security/ir.model.access.csv",
        #views
        "views/kojto_en1090_welding_parameters_views.xml",
        "views/kojto_en1090_equipment_views.xml",
        "views/kojto_en1090_document_bundles_views.xml",
        "views/kojto_en1090_wps_views.xml",
        "views/kojto_en1090_doc_control_views.xml",
        "views/kojto_en1090_doc_welding_tasks_views.xml",
        "views/kojto_en1090_weld_geometries_views.xml",
        "views/kojto_en1090_welding_specialists_views.xml",
        "views/kojto_en1090_welding_certificates_views.xml",
        "views/kojto_en1090_wpqrs_views.xml",
        "views/kojto_en1090_welding_processes_views.xml",
        "views/kojto_en1090_weld_depositions_views.xml",
        "views/kojto_en1090_translations_views.xml",
        "views/kojto_en1090_buttons.xml",
        "views/kojto_en1090_menu_views.xml",
        #reports
        "reports/kojto_en1090_report_actions.xml",
        "reports/kojto_en1090_document_bundles_templates.xml",
        "reports/kojto_en1090_doc_control_templates.xml",
        "reports/kojto_en1090_doc_performance_templates.xml",
        "reports/kojto_en1090_ce_label_templates.xml",
        "reports/kojto_en1090_wps_templates.xml",
        "reports/kojto_en1090_doc_welding_tasks_templates.xml",
    ],
    "installable": True,
    "application": True,
    "auto_install": False,
}
