{
    "name": "Kojto HR",
    "summary": "Human resources and employee management",
    "description": "Human resources module for managing employees, time tracking, business trips, leave management, and employee subcode rates",
    "author": "KOJTO",
    "website": "https://www.kojto.com",
    "category": "KOJTO",
    "version": "18.04.07",
    "depends": [
        "kojto_base",
        "kojto_commission_codes",
        "kojto_contacts",
        "kojto_library",
        "kojto_file_assets",
    ],
    "data": [
        "security/ir.model.access.csv",
        "security/ir.rule.csv",
        "views/kojto_hr_employees_views.xml",
        "views/kojto_hr_employee_subcode_rates_views.xml",
        "views/kojto_hr_employee_subcode_rates_dashboard_views.xml",
        "views/kojto_hr_time_tracking_views.xml",
        "views/kojto_hr_business_trips_views.xml",
        "views/kojto_hr_leave_management_views.xml",
        "views/kojto_hr_leave_types_views.xml",
        "views/kojto_hr_dashboard.xml",
        "views/kojto_hr_working_days_views.xml",
        "views/kojto_hr_calendar_event_views.xml",
        "views/kojto_hr_menu_views.xml",
        "views/kojto_hr_buttons.xml",
        "reports/kojto_hr_business_trips_templates.xml",
        "reports/kojto_hr_leave_management_templates.xml",
        "reports/kojto_hr_report_actions.xml",
        "actions/action_dropdown_view.xml",
        "actions/time_tracking_export_actions.xml",
        "data/autorun_function.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "/kojto_hr/static/src/css/calendar_custom.css",
            "/kojto_hr/static/src/js/time_input_mask.js",
        ],
    },
    "installable": True,
    "application": True,
    "auto_install": False,
}
